[sssd]
services = nss, pam
config_file_version = 2
domains = default

[domain/default]
id_provider = ldap
auth_provider = ldap

# Pointing to the IP you use for SSH
ldap_uri = ldap://192.168.56.101
ldap_search_base = dc=example,dc=com

# Standard LDAP schema and search settings
ldap_schema = rfc2307
ldap_user_search_base = dc=example,dc=com
ldap_group_search_base = dc=example,dc=com

# Disable TLS requirements for initial testing
ldap_tls_reqcert = allow
ldap_auth_disable_tls_never_use_in_production = true

cache_credentials = true
enumerate = true
